import typer
from rich.table import Table
from rich.text import Text
from rich import box
from clutch_cli.api import get_client
from clutch_cli.theme import console, DIM, SUCCESS, WARNING, header, footer


def insight():
    """Get your AI-generated weekly insight."""
    with get_client() as client:
        try:
            console.print()
            console.print(f"[{DIM}]Generating insight...[/{DIM}]")

            response = client.get("/insights/weekly")
            if response.status_code != 200:
                console.print("[bold red]Error: Failed to fetch insight.[/bold red]")
                raise typer.Exit(1)

            data = response.json()

            if "message" in data:
                console.print(f"[{WARNING}]{data['message']}[/{WARNING}]")
                raise typer.Exit()

            stats = data["stats"]
            summary = data["ai_summary"]

            header("WEEKLY INSIGHT")

            console.print(f"[{DIM}]Week of[/{DIM}] [bold white]{data['week_start']}[/bold white]")
            console.print()
            console.print(Text(summary, style="white"), soft_wrap=True)
            console.print()
            console.rule(style=DIM)
            console.print()

            table = Table(box=box.SIMPLE, show_header=False, pad_edge=False)
            table.add_column("Label", style=DIM, width=22)
            table.add_column("Value", style="bold white")

            table.add_row("Commits", f"[{SUCCESS}]{stats['total_commits']}[/{SUCCESS}]")
            table.add_row("Active Days", f"[{SUCCESS}]{stats['active_days']}[/{SUCCESS}]")
            table.add_row("Pull Requests", str(stats["total_prs"]))
            table.add_row("Issues", str(stats["total_issues"]))
            table.add_row("Best Day", str(stats["best_day"]))
            table.add_row("Generated by", f"[{DIM}]{data['generated_by']}[/{DIM}]")

            console.print(table)
            footer()

        except Exception:
            console.print("[bold red]Error: Could not connect to Clutch API.[/bold red]")
            raise typer.Exit(1)
